### ISSUE TITLE
Question: Debonding mechanism (attack?)

### ISSUE THREAD

**Issue by dwahdany** [renproject/ren#25]
I have a question regarding the continuous[ fee curve adjustment](https://github.com/renproject/ren/wiki/Fees-and-Economics) in context with the bonding.

1. Is it possible to remove a bond and if so, what are the conditions?
If so:
2. Is it possible to remove large amounts of B without risk or fee?
3. Is it therefore a feasible attack to remove large amounts of bonded REN to sharply increase the continuous fee and rendering many renBTC, since the maximum fee **per second** goes up to 100%, completely worthless in short time?
4. Is there a mechanism to prevent such a debonding attack or is it simply deemed infeasible due to the capital required?

I'm not so sure this would be a rational attack, since it still requires owning many REN which would lose in value. But then again something like borrowing renBTC for BTC collateral and minting BTC before executing a debonding devaluation attack could make this rationally profitable.

**Comment by MaximilianR** [comment]
1) Currently it takes a minimum of 2 epochs to unbond (~28-56 days). This parameter could be set at any reasonable value
2) During the deregistration period you do not earn rewards, so there is a cost of capital lock-up
3) The continuous fee model has been deprecated
4) See above answers

**Comment by dwahdany** [comment]
>     1. Currently it takes a minimum of 2 epochs to unbond (~28-56 days). This parameter could be set at any reasonable value
> 
>     2. During the deregistration period you do not earn rewards, so there is a cost of capital lock-up
> 
>     3. The continuous fee model has been deprecated
> 
>     4. See above answers

Do you have a reference for 3 or is it not publicly documented yet? If there is no continuous fee then this whole issue is resolved, so I will close it after your response.

**Comment by MaximilianR** [comment]
Don't have any particular post to provide as reference here, but it's been communicated by the core team publicly multiple times that continuous fees should not be implemented even if it is possible (I'm also on the core team). This wiki will be updated in the future when most of the core parts of RenVM have been built out, since they are currently subject as development progresses
