### ISSUE TITLE
Question about minting and burning

### ISSUE THREAD

**Issue by elias-stb** [renproject/ren#26]
Hi, I'm interested in the minting and burning process for tax purposes. If I exchange BTC for WBTC and then WBTC back to BTC, do I get the exact same Bitcoin back? Like the exact same coin or just the right amount?
Thanks:)

**Comment by MaximilianR** [comment]
You would not get the same BTC back if you are talking about the same UTXO, because it wouldn't make renBTC/wBTC fungible tokens that could be swapped and redeemed at any amount

**Comment by elias-stb** [comment]
Thank you @MaximilianR, your answer has helped me a lot with understanding the process!
