### ISSUE TITLE
Questions about bribery attacks and ability to restore one-to-one peg

### ISSUE THREAD

**Issue by Stumble** [renproject/ren#8]
Great project! Two questions.

> Shards are large, containing at least one hundred Darknodes, and they are randomly shuffled once per day. This makes Sybil attacks difficult, as an attacker needs to own a large portion of the entire network to have a chance at corrupting any one shard. This also makes bribery attacks extremely difficult, requiring an attacker to collude with a large number of anonymous Darknodes in a short period of time, with minimal trust.

What's the level of the anonymity of darknodes? Or to be more specific, assume that I am a bribery attacker, is it possible for me to contact those selected nodes? If that's possible, I can imagine that attackers can make a deal with nodes in the shards, even with minimal trust, as in the blockchain world, they may be able to create a smart contract to eliminate the need of trust.

> These properties help RenVM to resist attacks made by irrational adversaries (adversaries that do not care about profiting from an attack). But, it also helps RenVM to resist attacks from rational adversaries during periods where an attack may be temporarily profitable. Regardless, RenVM is always able to restore its one-to-one peg in the unlikely event that an attack succeeds.
What's the process of restoring the one-to-one peg when an attack succeeded?

**Comment by askucher** [comment]
There is the proof of shuffle once per day? Where can I read the doc?
